# This rule is not used by the project rclone-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to abarrak.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rclone-operator
    app.kubernetes.io/managed-by: kustomize
  name: rclone-viewer-role
rules:
- apiGroups:
  - abarrak.com
  resources:
  - rclones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - abarrak.com
  resources:
  - rclones/status
  verbs:
  - get
