---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - abarrak.com
  resources:
  - rclones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - abarrak.com
  resources:
  - rclones/finalizers
  verbs:
  - update
- apiGroups:
  - abarrak.com
  resources:
  - rclones/status
  verbs:
  - get
  - patch
  - update
